#!/usr/bin/env bash

# ###############################################################
# PATHS
# ###############################################################

# Set home.
export CORDEX_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Ensure target scripts are executable.
chmod a+x "$CORDEX_HOME"/sh/*/*.sh

# Set python path.
export PYTHONPATH="$CORDEX_HOME":"$PYTHONPATH"
export PYTHONPATH="$CORDEX_HOME/repos/libs/esdoc-py-client":"$PYTHONPATH"
export PYTHONPATH="$CORDEX_HOME/repos/libs/pyessv":"$PYTHONPATH"

# ###############################################################
# UTILS
# ###############################################################

source "$CORDEX_HOME"/sh/utils/main.sh

# ###############################################################
# COMMAND EXECUTION
# ###############################################################

# Command executor.
exec_cmd()
{
	log_banner
	log $1" :: BEGINS"
	activate_venv
	log_banner

	target=$"$CORDEX_HOME"/sh/$2
	if [ "$3" ] && [ "$4" ] && [ "$5" ]; then
		source $target $3 $4 $5
	elif [ "$3" ] && [ "$4" ]; then
		source $target $3 $4 ""
	elif [ "$3" ]; then
		source $target $3 "" ""
	else
		source $target ""
	fi

	log_banner
	log $1" :: ENDS"
	log_banner
}

# ###############################################################
# ALIASES
# ###############################################################

# ... setup
alias cordex-setup='exec_cmd setup utils/setup.sh'

# Citations
alias cordex-citations-init-xls='exec_cmd citations-init-xls citations/init_xls.sh $1'
alias cordex-citations-generate-json='exec_cmd citations-generate-json citations/generate_json.sh $1'

# Institutes
alias cordex-institutes-list='exec_cmd institutes-list institutes/list.sh'
alias cordex-institutes-gh-repos-add='exec_cmd institutes-gh-repos-clone institutes/gh_repos_add.sh'
alias cordex-institutes-gh-repos-clean='exec_cmd institutes-gh-repos-clone institutes/gh_repos_clean.sh'
alias cordex-institutes-gh-repos-create='exec_cmd institutes-gh-repos-sync institutes/gh_repos_create.sh'
alias cordex-institutes-gh-repos-init-gitignore='exec_cmd institutes-gh-repos-clone institutes/gh_repos_init_gitignore.sh'
alias cordex-institutes-gh-repos-pull='exec_cmd institutes-gh-repos-pull institutes/gh_repos_pull.sh'
alias cordex-institutes-gh-repos-push='exec_cmd institutes-gh-repos-push institutes/gh_repos_push.sh'
alias cordex-institutes-gh-repos-reclone='exec_cmd institutes-gh-repos-clone institutes/gh_repos_reclone.sh'
alias cordex-institutes-gh-repos-reset='exec_cmd institutes-gh-repos-push institutes/gh_repos_reset.sh'
alias cordex-institutes-gh-repos-status='exec_cmd institutes-gh-repos-clone institutes/gh_repos_status.sh'
alias cordex-institutes-gh-repos-verify='exec_cmd institutes-gh-repos-verify institutes/gh_repos_verify.sh $1'

# Models
# alias cordex-models-archive-cim-documents='exec_cmd models-archive-cim-documents models/archive_cim_documents.sh'
# alias cordex-models-generate-cim='exec_cmd models-generate-cim models/generate_cim.sh'
# alias cordex-models-generate-json='exec_cmd models-generate-json models/generate_json.sh'
alias cordex-models-generate-xls='exec_cmd models-generate-xls models/generate_xls.sh'
# alias cordex-models-reset-cim='exec_cmd models-reset-cim models/reset_cim.sh'
# alias cordex-models-reset-json='exec_cmd models-reset-json models/reset_json.sh'

# Parties
alias cordex-parties-init-xls='exec_cmd parties-init-xls parties/init_xls.sh $1'
alias cordex-parties-generate-json='exec_cmd parties-generate-json parties/generate_json.sh $1'

# Specializations
alias cordex-specializations-generate='exec_cmd specializations-generate specializations/generate.sh'
alias cordex-specializations-repos-pull='exec_cmd specializations-pull specializations/gh_repos_pull.sh'
alias cordex-specializations-repos-push='exec_cmd specializations-push specializations/gh_repos_push.sh'
alias cordex-specializations-repos-status='exec_cmd specializations-status specializations/gh_repos_status.sh'
alias cordex-specializations-sync-cim-profile='exec_cmd specializations-sync-cim-profile specializations/sync_cim_profile.sh'
alias cordex-specializations-sync-definitions='exec_cmd specializations-sync-definitions specializations/sync_definitions.sh'
alias cordex-specializations-sync-tooling='exec_cmd specializations-sync-tooling specializations/sync_tooling.sh'
alias cordex-specializations-validate='exec_cmd specializations-validate specializations/validate.sh'

# Vocabs
alias cordex-vocabs-write-bash-vars='exec_cmd vocabs-write-bash-vars vocabs/write_bash_vars.sh'
