#!/bin/bash

# ###############################################################
# SECTION: VOCABULARY BASH VARS
# ###############################################################

# Institute - canonical name
declare -a INSTITUTE=(
	'auth-lhtee'
	'auth-met'
	'awi'
	'bccr'
	'cccma'
	'chmi'
	'clmcom'
	'cnrm'
	'crp-gl'
	'cuni'
	'dhmz'
	'dmi'
	'enea'
	'gerics'
	'hms'
	'ictp'
	'idl'
	'iitm'
	'ipsl'
	'ipsl-ineris'
	'knmi'
	'mgo'
	'miub'
	'mohc'
	'mpi-csc'
	'nuim'
	'rmib-ugent'
	'smhi'
	'ucan'
	'uclm'
	'uhoh'
	'ulg'
	'uqam'
)

# Institute - raw name
declare -a INSTITUTE_RAW=(
	'AUTH-LHTEE'
	'AUTH-Met'
	'AWI'
	'BCCR'
	'CCCma'
	'CHMI'
	'CLMcom'
	'CNRM'
	'CRP-GL'
	'CUNI'
	'DHMZ'
	'DMI'
	'ENEA'
	'GERICS'
	'HMS'
	'ICTP'
	'IDL'
	'IITM'
	'IPSL'
	'IPSL-INERIS'
	'KNMI'
	'MGO'
	'MIUB'
	'MOHC'
	'MPI-CSC'
	'NUIM'
	'RMIB-UGent'
	'SMHI'
	'UCAN'
	'UCLM'
	'UHOH'
	'ULg'
	'UQAM'
)

# Source ID - canonical name
declare -a RCM_MODEL=(
	'auth-lhtee-wrf321b'
	'auth-met-wrf331a'
	'awi-hirham5'
	'bccr-wrf331'
	'bccr-wrf331c'
	'cccma-canrcm4'
	'chmi-aladin52'
	'clmcom-cclm4-8-17'
	'cnrm-aladin52'
	'cnrm-aladin53'
	'cnrm-aladin63'
	'cnrm-arpege51'
	'cnrm-arpege52'
	'crp-gl-wrf331a'
	'cuni-regcm4-2'
	'dhmz-regcm4-2'
	'dmi-hirham5'
	'enea-regcm4-3'
	'gerics-remo2009'
	'hms-aladin52'
	'ictp-regcm4-3'
	'idl-wrf331d'
	'iitm-regcm4-1'
	'iitm-regcm4-4'
	'ipsl-ineris-wrf331f'
	'ipsl-wrf381p'
	'knmi-racmo21p'
	'knmi-racmo22e'
	'knmi-racmo22t'
	'mgo-rrcm'
	'miub-wrf331a'
	'mohc-hadgem3-ra'
	'mohc-hadrm3p'
	'mpi-csc-remo2009'
	'nuim-wrf331f'
	'rmib-ugent-alaro-0'
	'smhi-rca4'
	'smhi-rca4-sn'
	'smhi-rcao'
	'smhi-rcao-sn'
	'ucan-wrf331g'
	'ucan-wrf350i'
	'uclm-promes'
	'uhoh-wrf331h'
	'ulg-mar36'
	'uqam-crcm5'
)

# Source ID - raw name
declare -a RCM_MODEL_RAW=(
	'AUTH-LHTEE-WRF321B'
	'AUTH-Met-WRF331A'
	'AWI-HIRHAM5'
	'BCCR-WRF331'
	'BCCR-WRF331C'
	'CCCma-CanRCM4'
	'CHMI-ALADIN52'
	'CLMcom-CCLM4-8-17'
	'CNRM-ALADIN52'
	'CNRM-ALADIN53'
	'CNRM-ALADIN63'
	'CNRM-ARPEGE51'
	'CNRM-ARPEGE52'
	'CRP-GL-WRF331A'
	'CUNI-RegCM4-2'
	'DHMZ-RegCM4-2'
	'DMI-HIRHAM5'
	'ENEA-RegCM4-3'
	'GERICS-REMO2009'
	'HMS-ALADIN52'
	'ICTP-RegCM4-3'
	'IDL-WRF331D'
	'IITM-RegCM4-1'
	'IITM-RegCM4-4'
	'IPSL-INERIS-WRF331F'
	'IPSL-WRF381P'
	'KNMI-RACMO21P'
	'KNMI-RACMO22E'
	'KNMI-RACMO22T'
	'MGO-RRCM'
	'MIUB-WRF331A'
	'MOHC-HadGEM3-RA'
	'MOHC-HadRM3P'
	'MPI-CSC-REMO2009'
	'NUIM-WRF331F'
	'RMIB-UGent-ALARO-0'
	'SMHI-RCA4'
	'SMHI-RCA4-SN'
	'SMHI-RCAO'
	'SMHI-RCAO-SN'
	'UCAN-WRF331G'
	'UCAN-WRF350I'
	'UCLM-PROMES'
	'UHOH-WRF331H'
	'ULg-MAR36'
	'UQAM-CRCM5'
)

# ###############################################################
# SECTION: ES-DOC SPECIALZATIONS
# ###############################################################

# Array of specifications.
declare -a CORDEXP_SPECIALIZATIONS=(
	'toplevel'
)
