#!/usr/bin/env bash

# ###############################################################
# SECTION: VOCABULARY BASH VARS
# ###############################################################

# Institute - canonical name
export CORDEX_INSTITUTION_ID=(
[INSTITUTE])

# Institute - raw name
export CORDEX_INSTITUTION_ID_RAW=(
[INSTITUTE_RAW])

# Source ID - canonical name
export CORDEX_RCM_MODEL=(
[RCM_MODEL])

# Source ID - raw name
export CORDEX_RCM_MODEL_RAW=(
[RCM_MODEL_RAW])

# ###############################################################
# SECTION: ES-DOC SPECIALZATIONS
# ###############################################################

# Array of specifications.
export CORDEX_SPECIALIZATIONS=(
	'toplevel'
	'atmos'
)
