#!/usr/bin/env bash

# ###############################################################
# SECTION: VOCABULARY BASH VARS
# ###############################################################

# CORDEX: Institute - canonical name
export CORDEX_INSTITUTION_ID=(
[__CORDEX_INSTITUTION_ID__])

# CORDEX: Institute - raw name
export CORDEX_INSTITUTION_ID_RAW=(
[__CORDEX_INSTITUTION_ID_RAW__])

# CORDEXP: Institute - canonical name
export CORDEXP_INSTITUTION_ID=(
[__CORDEXP_INSTITUTION_ID__])

# CORDEXP: Institute - raw name
export CORDEXP_INSTITUTION_ID_RAW=(
[__CORDEXP_INSTITUTION_ID_RAW__])

# CORDEXP: Source ID - canonical name
export CORDEXP_RCM_MODEL=(
[__CORDEXP_RCM_MODEL__])

# CORDEXP: Source ID - raw name
export CORDEXP_RCM_MODEL_RAW=(
[__CORDEXP_RCM_MODEL_RAW__])

# ###############################################################
# SECTION: ES-DOC SPECIALZATIONS
# ###############################################################

# Array of specifications.
export CORDEXP_SPECIALIZATIONS=(
	'toplevel'
	'atmos'
)
