#!/usr/bin/env bash

# ###############################################################
# SECTION: VOCABULARY BASH VARS
# ###############################################################

# Institute - canonical name
export CORDEXP_INSTITUTION_ID=(
[INSTITUTION_ID])

# Institute - raw name
export CORDEXP_INSTITUTION_ID_RAW=(
[INSTITUTION_ID_RAW])

# Source ID - canonical name
export CORDEXP_RCM_MODEL=(
[RCM_MODEL])

# Source ID - raw name
export CORDEXP_RCM_MODEL_RAW=(
[RCM_MODEL_RAW])

# ###############################################################
# SECTION: ES-DOC SPECIALZATIONS
# ###############################################################

# Array of specifications.
export CORDEXP_SPECIALIZATIONS=(
	'toplevel'
	'atmos'
)
